FROM python:3

RUN mkdir -p /scripts
WORKDIR /scripts

COPY . ./

RUN pip install --no-cache-dir -r requirement.txt
RUN python3 -m nltk.downloader -d /usr/local/share/nltk_data stopwords wordnet punkt averaged_perceptron_tagger \
vader_lexicon sentiwordnet