# Base image is an Ubuntu based
FROM python:3

RUN apt-get -qq -y update && apt-get -qq -y install cron

RUN mkdir -p /scripts
WORKDIR /scripts

COPY . ./

# Install pyClowder and any other python dependencies
RUN pip3 install --no-cache-dir -r requirement.txt
RUN python3 -m nltk.downloader -d /usr/local/share/nltk_data stopwords wordnet punkt averaged_perceptron_tagger \
vader_lexicon sentiwordnet

# cron job clean tmp folder
RUN chmod u+x ./clear_cache.sh
RUN chmod 0644 ./clear_cache_cron
RUN crontab ./clear_cache_cron

# Command to be run when container is run
# Can add heartbeat to change the refresh rate
CMD python3 CorrMatrixExtractor.py --heartbeat 40 --num 2

ENV MAIN_SCRIPT="CorrMatrixExtractor.py"
