FROM python:3

RUN mkdir -p /scripts
WORKDIR /scripts

# copy paste python scripts
COPY . ./

# install dependency libraries and download required data
RUN pip install --no-cache-dir -r requirement.txt
