FROM continuumio/anaconda3

RUN mkdir -p /scripts
WORKDIR /scripts

# copy paste python scripts
COPY . ./

# install dependency libraries
RUN apt-get update
RUN apt-get -y install nodejs npm

# install dependency libraries and download required data
RUN conda install -c plotly plotly-orca psutil requests
RUN pip install -r requirement.txt
