version: "3.3"

services:

  rabbitmq:
    image: rabbitmq:3-management
    ports:
    - "5672:5672"
    - "15672:15672"
    volumes:
    - "rabbitmq_data:/data"

  algorithm_botometer_check_bot:
    build: ./botometer_check_bot
    image: botometer_check_bot:latest
    depends_on:
    - rabbitmq
    command: python ./botometer_check_bot.py
    environment:
    - AWS_ACCESSKEY=${AWS_ACCESSKEY}
    - AWS_ACCESSKEYSECRET=${AWS_ACCESSKEYSECRET}
    restart: unless-stopped

  algorithm_bulk_comparison:
    build: ./bulk_comparison
    image: bulk_comparison:latest
    depends_on:
    - rabbitmq
    command: python ./bulk_comparison.py
    environment:
    - AWS_ACCESSKEY=${AWS_ACCESSKEY}
    - AWS_ACCESSKEYSECRET=${AWS_ACCESSKEYSECRET}
    restart: unless-stopped

  algorithm_check_screen_name:
    build: ./check_screen_name
    image: check_screen_name:latest
    depends_on:
    - rabbitmq
    command: python ./check_screen_name.py
    environment:
    - AWS_ACCESSKEY=${AWS_ACCESSKEY}
    - AWS_ACCESSKEYSECRET=${AWS_ACCESSKEYSECRET}
    restart: unless-stopped

  algorithm_collect_timeline:
    build: ./collect_timeline
    image: collect_timeline:latest
    depends_on:
    - rabbitmq
    command: python ./collect_timeline.py
    environment:
    - AWS_ACCESSKEY=${AWS_ACCESSKEY}
    - AWS_ACCESSKEYSECRET=${AWS_ACCESSKEYSECRET}
    restart: unless-stopped

  algorithm_get_personality:
    build: ./get_personality
    image: get_personality:latest
    depends_on:
    - rabbitmq
    command: python ./get_personality.py
    environment:
    - AWS_ACCESSKEY=${AWS_ACCESSKEY}
    - AWS_ACCESSKEYSECRET=${AWS_ACCESSKEYSECRET}
    restart: unless-stopped

  algorithm_get_sim_score:
    build: ./get_sim_score
    image: get_sim_score:latest
    depends_on:
    - rabbitmq
    command: python ./get_sim_score.py
    environment:
    - AWS_ACCESSKEY=${AWS_ACCESSKEY}
    - AWS_ACCESSKEYSECRET=${AWS_ACCESSKEYSECRET}
    restart: unless-stopped

  algorithm_screen_name_prompt:
    build: ./screen_name_prompt
    image: screen_name_prompt:latest
    depends_on:
    - rabbitmq
    command: python ./screen_name_prompt.py
    environment:
    - AWS_ACCESSKEY=${AWS_ACCESSKEY}
    - AWS_ACCESSKEYSECRET=${AWS_ACCESSKEYSECRET}
    restart: unless-stopped

  bae_server:
    image: bae-server:latest
    depends_on:
    - rabbitmq
    - algorithm_botometer_check_bot
    - algorithm_bulk_comparison
    - algorithm_check_screen_name
    - algorithm_collect_timeline
    - algorithm_get_personality
    - algorithm_get_sim_score
    - algorithm_screen_name_prompt
    ports:
    - "8001:8001"
    command: npm start
    environment:
    - AWS_ACCESSKEY=${AWS_ACCESSKEY}
    - AWS_ACCESSKEYSECRET=${AWS_ACCESSKEYSECRET}
    - TWITTER_CONSUMER_KEY=${TWITTER_CONSUMER_KEY}
    - TWITTER_CONSUMER_SECRET=${TWITTER_CONSUMER_SECRET}
    - MASHAPE_APIKEY=${MASHAPE_APIKEY}
    restart: unless-stopped

volumes:
  rabbitmq_data: