version: "3.3"

services:
  algorithm_botometer_check_bot:
    image: botometer_check_bot:latest
#    depends_on:
#    - rabbitmq
    restart: unless-stopped
  algorithm_bulk_comparison:
    image: bulk_comparison:latest
#    depends_on:
#    - rabbitmq
    restart: unless-stopped
  algorithm_check_screen_name:
    image: check_screen_name:latest
#    depends_on:
#    - rabbitmq
    restart: unless-stopped
  algorithm_collect_timeline:
    image: collect_timeline:latest
#    depends_on:
#    - rabbitmq
    restart: unless-stopped
  algorithm_get_personality:
    image: get_personality:latest
#    depends_on:
#    - rabbitmq
    restart: unless-stopped
  algorithm_get_sim_score:
    image: get_sim_score:latest
#    depends_on:
#    - rabbitmq
    restart: unless-stopped
  algorithm_screen_name_prompt:
    image: screen_name_prompt:latest
#    depends_on:
#    - rabbitmq
    restart: unless-stopped
#    networks:
#    -
#    ports:
#    - 9000:9000
#    environment:
#    - APPLICATION_SECRET=${APPLICATION_SECRET:-notasecret}
# Configs for docker swarm deployment (WIP)
#    configs:
#    - source: api_config
#      target: /home/geostreams/application.conf
#      uid: '103'
#      gid: '103'
#      mode: 0440
#    volumes:
#    - ${PWD}/conf/application.conf:/home/geostreams/conf/application.conf

