version: "3.3"

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
    - "5672:5672"
    - "15672:15672"

  minio:
    image: minio/minio
    hostname: minio
    ports:
    - "9000:9000"
    volumes:
    - "smile_content_data:/tmp"
    command: server /tmp
    environment:
    - MINIO_ACCESS_KEY=${AWS_ACCESSKEY}
    - MINIO_SECRET_KEY=${AWS_ACCESSKEYSECRET}
    restart: unless-stopped

  redis:
    image: redis
    hostname: redis
#    ports:
#    - "6379:6379"
    restart: unless-stopped

  nginx:
    build: ./nginx
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    depends_on:
      - smile-server
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    restart: unless-stopped

  algorithm-classification-predict:
#    build: ./classification_predict
    image: socialmediamacroscope/classification_predict:0.1.1
    depends_on:
    - rabbitmq
    - minio
    command: python ./rabbitmq_handler.py
    environment:
    - MINIO_URL=${MINIO_URL}
    - MINIO_PUBLIC_ACCESS_URL=${MINIO_PUBLIC_ACCESS_URL}
    - RABBITMQ_HOST=${RABBITMQ_HOST}
    - AWS_ACCESSKEY=${AWS_ACCESSKEY}
    - AWS_ACCESSKEYSECRET=${AWS_ACCESSKEYSECRET}
    - BUCKET_NAME=${BUCKET_NAME}
    - QUEUE_NAME=classification_predict
    restart: unless-stopped

  algorithm-classification-split:
#    build: ./classification_split
    image: socialmediamacroscope/classification_split:0.1.1
    depends_on:
    - rabbitmq
    - minio
    command: python ./rabbitmq_handler.py
    environment:
    - MINIO_URL=${MINIO_URL}
    - MINIO_PUBLIC_ACCESS_URL=${MINIO_PUBLIC_ACCESS_URL}
    - RABBITMQ_HOST=${RABBITMQ_HOST}
    - AWS_ACCESSKEY=${AWS_ACCESSKEY}
    - AWS_ACCESSKEYSECRET=${AWS_ACCESSKEYSECRET}
    - BUCKET_NAME=${BUCKET_NAME}
    - QUEUE_NAME=classification_split
    restart: unless-stopped

  algorithm-classification-train:
#    build: ./classification_train
    image: socialmediamacroscope/classification_train:0.1.1
    depends_on:
    - rabbitmq
    - minio
    command: python ./rabbitmq_handler.py
    environment:
    - MINIO_URL=${MINIO_URL}
    - MINIO_PUBLIC_ACCESS_URL=${MINIO_PUBLIC_ACCESS_URL}
    - RABBITMQ_HOST=${RABBITMQ_HOST}
    - AWS_ACCESSKEY=${AWS_ACCESSKEY}
    - AWS_ACCESSKEYSECRET=${AWS_ACCESSKEYSECRET}
    - BUCKET_NAME=${BUCKET_NAME}
    - QUEUE_NAME=classification_train
    restart: unless-stopped

  algorithm-histogram:
#    build: ./histogram
    image: socialmediamacroscope/histogram:0.1.1
    depends_on:
    - rabbitmq
    - minio
    command: python ./rabbitmq_handler.py
    environment:
    - MINIO_URL=${MINIO_URL}
    - MINIO_PUBLIC_ACCESS_URL=${MINIO_PUBLIC_ACCESS_URL}
    - RABBITMQ_HOST=${RABBITMQ_HOST}
    - AWS_ACCESSKEY=${AWS_ACCESSKEY}
    - AWS_ACCESSKEYSECRET=${AWS_ACCESSKEYSECRET}
    - BUCKET_NAME=${BUCKET_NAME}
    - QUEUE_NAME=histogram
    restart: unless-stopped

  algorithm-network-analysis:
#    build: ./network_analysis
    image: socialmediamacroscope/network_analysis:0.1.1
    depends_on:
    - rabbitmq
    - minio
    command: python ./rabbitmq_handler.py
    environment:
    - MINIO_URL=${MINIO_URL}
    - MINIO_PUBLIC_ACCESS_URL=${MINIO_PUBLIC_ACCESS_URL}
    - RABBITMQ_HOST=${RABBITMQ_HOST}
    - AWS_ACCESSKEY=${AWS_ACCESSKEY}
    - AWS_ACCESSKEYSECRET=${AWS_ACCESSKEYSECRET}
    - BUCKET_NAME=${BUCKET_NAME}
    - QUEUE_NAME=network_analysis
    - EMAIL_HOST=${EMAIL_HOST}
    - EMAIL_PORT=${EMAIL_PORT}
    - EMAIL_FROM_ADDRESS=${EMAIL_FROM_ADDRESS}
    - EMAIL_PASSWORD=${EMAIL_PASSWORD}
    restart: unless-stopped

  algorithm-preprocessing:
#    build: ./preprocessing
    image: socialmediamacroscope/preprocessing:0.1.1
    depends_on:
    - rabbitmq
    - minio
    command: python ./rabbitmq_handler.py
    environment:
    - MINIO_URL=${MINIO_URL}
    - MINIO_PUBLIC_ACCESS_URL=${MINIO_PUBLIC_ACCESS_URL}
    - RABBITMQ_HOST=${RABBITMQ_HOST}
    - AWS_ACCESSKEY=${AWS_ACCESSKEY}
    - AWS_ACCESSKEYSECRET=${AWS_ACCESSKEYSECRET}
    - BUCKET_NAME=${BUCKET_NAME}
    - QUEUE_NAME=preprocessing
    - EMAIL_HOST=${EMAIL_HOST}
    - EMAIL_PORT=${EMAIL_PORT}
    - EMAIL_FROM_ADDRESS=${EMAIL_FROM_ADDRESS}
    - EMAIL_PASSWORD=${EMAIL_PASSWORD}
    restart: unless-stopped

  algorithm-sentiment-analysis:
#    build: ./sentiment_analysis
    image: socialmediamacroscope/sentiment_analysis:0.1.3
    depends_on:
    - rabbitmq
    - minio
    command: python ./rabbitmq_handler.py
    environment:
    - MINIO_URL=${MINIO_URL}
    - MINIO_PUBLIC_ACCESS_URL=${MINIO_PUBLIC_ACCESS_URL}
    - RABBITMQ_HOST=${RABBITMQ_HOST}
    - AWS_ACCESSKEY=${AWS_ACCESSKEY}
    - AWS_ACCESSKEYSECRET=${AWS_ACCESSKEYSECRET}
    - BUCKET_NAME=${BUCKET_NAME}
    - QUEUE_NAME=sentiment_analysis
    - EMAIL_HOST=${EMAIL_HOST}
    - EMAIL_PORT=${EMAIL_PORT}
    - EMAIL_FROM_ADDRESS=${EMAIL_FROM_ADDRESS}
    - EMAIL_PASSWORD=${EMAIL_PASSWORD}
    restart: unless-stopped

  algorithm-screen-name-prompt:
#    build: ./screen_name_prompt
    image: socialmediamacroscope/screen_name_prompt:0.1.1
    depends_on:
    - rabbitmq
    - minio
    command: python ./screen_name_prompt.py
    environment:
    - MINIO_URL=${MINIO_URL}
    - MINIO_PUBLIC_ACCESS_URL=${MINIO_PUBLIC_ACCESS_URL}
    - RABBITMQ_HOST=${RABBITMQ_HOST}
    - AWS_ACCESSKEY=${AWS_ACCESSKEY}
    - AWS_ACCESSKEYSECRET=${AWS_ACCESSKEYSECRET}
    - BUCKET_NAME=${BUCKET_NAME}
    - QUEUE_NAME=bae_screen_name_prompt
    restart: unless-stopped

  algorithm-topic-modeling:
#    build: ./topic_modeling
    image: socialmediamacroscope/topic_modeling:0.1.1
    depends_on:
    - rabbitmq
    - minio
    command: python ./rabbitmq_handler.py
    environment:
    - MINIO_URL=${MINIO_URL}
    - MINIO_PUBLIC_ACCESS_URL=${MINIO_PUBLIC_ACCESS_URL}
    - RABBITMQ_HOST=${RABBITMQ_HOST}
    - AWS_ACCESSKEY=${AWS_ACCESSKEY}
    - AWS_ACCESSKEYSECRET=${AWS_ACCESSKEYSECRET}
    - BUCKET_NAME=${BUCKET_NAME}
    - QUEUE_NAME=topic_modeling
    - EMAIL_HOST=${EMAIL_HOST}
    - EMAIL_PORT=${EMAIL_PORT}
    - EMAIL_FROM_ADDRESS=${EMAIL_FROM_ADDRESS}
    - EMAIL_PASSWORD=${EMAIL_PASSWORD}
    restart: unless-stopped

  algorithm-name-entity-recognition:
#    build: ./name_entity_recognition
    image: socialmediamacroscope/name_entity_recognition:0.1.0
    depends_on:
    - rabbitmq
    - minio
    command: python3 ./rabbitmq_handler.py
    environment:
    - MINIO_URL=${MINIO_URL}
    - MINIO_PUBLIC_ACCESS_URL=${MINIO_PUBLIC_ACCESS_URL}
    - RABBITMQ_HOST=${RABBITMQ_HOST}
    - AWS_ACCESSKEY=${AWS_ACCESSKEY}
    - AWS_ACCESSKEYSECRET=${AWS_ACCESSKEYSECRET}
    - BUCKET_NAME=${BUCKET_NAME}
    - QUEUE_NAME=name_entity_recognition
    - EMAIL_HOST=${EMAIL_HOST}
    - EMAIL_PORT=${EMAIL_PORT}
    - EMAIL_FROM_ADDRESS=${EMAIL_FROM_ADDRESS}
    - EMAIL_PASSWORD=${EMAIL_PASSWORD}
    restart: unless-stopped

  algorithm-autophrase:
#    build: ./autophrase
    image: socialmediamacroscope/autophrase:0.1.2
    depends_on:
    - rabbitmq
    - minio
    command: python3 ./rabbitmq_handler.py
    environment:
    - MINIO_URL=${MINIO_URL}
    - MINIO_PUBLIC_ACCESS_URL=${MINIO_PUBLIC_ACCESS_URL}
    - RABBITMQ_HOST=${RABBITMQ_HOST}
    - AWS_ACCESSKEY=${AWS_ACCESSKEY}
    - AWS_ACCESSKEYSECRET=${AWS_ACCESSKEYSECRET}
    - BUCKET_NAME=${BUCKET_NAME}
    - QUEUE_NAME=autophrase
    - EMAIL_HOST=${EMAIL_HOST}
    - EMAIL_PORT=${EMAIL_PORT}
    - EMAIL_FROM_ADDRESS=${EMAIL_FROM_ADDRESS}
    - EMAIL_PASSWORD=${EMAIL_PASSWORD}
    restart: unless-stopped

  image-crawler:
#    build: ./image_crawler
    image: socialmediamacroscope/image_crawler:0.1.1
    depends_on:
    - rabbitmq
    - minio
    command: python3 ./rabbitmq_handler.py
    environment:
    - MINIO_URL=${MINIO_URL}
    - MINIO_PUBLIC_ACCESS_URL=${MINIO_PUBLIC_ACCESS_URL}
    - RABBITMQ_HOST=${RABBITMQ_HOST}
    - AWS_ACCESSKEY=${AWS_ACCESSKEY}
    - AWS_ACCESSKEYSECRET=${AWS_ACCESSKEYSECRET}
    - BUCKET_NAME=${BUCKET_NAME}
    - QUEUE_NAME=image_crawler
    - EMAIL_HOST=${EMAIL_HOST}
    - EMAIL_PORT=${EMAIL_PORT}
    - EMAIL_FROM_ADDRESS=${EMAIL_FROM_ADDRESS}
    - EMAIL_PASSWORD=${EMAIL_PASSWORD}
    restart: unless-stopped

  collect-reddit-comment:
#    build: ./collect_reddit_comment
    image: socialmediamacroscope/collect_reddit_comment:0.1.1
    depends_on:
    - rabbitmq
    - minio
    command: python3 ./rabbitmq_handler.py
    environment:
    - MINIO_URL=${MINIO_URL}
    - MINIO_PUBLIC_ACCESS_URL=${MINIO_PUBLIC_ACCESS_URL}
    - RABBITMQ_HOST=${RABBITMQ_HOST}
    - REDDIT_CLIENT_ID=${REDDIT_CLIENT_ID}
    - REDDIT_CLIENT_SECRET=${REDDIT_CLIENT_SECRET}
    - AWS_ACCESSKEY=${AWS_ACCESSKEY}
    - AWS_ACCESSKEYSECRET=${AWS_ACCESSKEYSECRET}
    - BUCKET_NAME=${BUCKET_NAME}
    - QUEUE_NAME=reddit_comment
    - EMAIL_HOST=${EMAIL_HOST}
    - EMAIL_PORT=${EMAIL_PORT}
    - EMAIL_FROM_ADDRESS=${EMAIL_FROM_ADDRESS}
    - EMAIL_PASSWORD=${EMAIL_PASSWORD}
    restart: unless-stopped

  smile-server:
#    build: /Users/cwang138/Documents/Macroscope/SMILE/www
    image: socialmediamacroscope/smile_server:0.2.5
    depends_on:
    - rabbitmq
    - minio
    - redis
    - algorithm-classification-predict
    - algorithm-classification-split
    - algorithm-classification-train
    - algorithm-histogram
    - algorithm-network-analysis
    - algorithm-preprocessing
    - algorithm-sentiment-analysis
    - algorithm-autophrase
    - algorithm-name-entity-recognition
    - algorithm-topic-modeling
    - algorithm-screen-name-prompt
    - clowder-create-collection
    - clowder-create-dataset
    - clowder-create-space
    - clowder-list
    - clowder-upload-file
    ports:
    - "8001:8001"
    command: npm run docker-start
    environment:
    - HOME=${HOME}
    - DOCKERIZED=${DOCKERIZED}
    - LOCAL_ALGORITHM=${LOCAL_ALGORITHM}
    - MINIO_URL=${MINIO_URL}
    - REDIS_URL=${REDIS_URL}
    - SMILE_GRAPHQL_URL=${SMILE_GRAPHQL_URL}
    - RABBITMQ_URL=${RABBITMQ_URL}
    - BUCKET_NAME=${BUCKET_NAME}
    - AWS_ACCESSKEY=${AWS_ACCESSKEY}
    - AWS_ACCESSKEYSECRET=${AWS_ACCESSKEYSECRET}
    - TWITTER_CONSUMER_KEY=${TWITTER_CONSUMER_KEY}
    - TWITTER_CONSUMER_SECRET=${TWITTER_CONSUMER_SECRET}
    - REDDIT_CLIENT_ID=${REDDIT_CLIENT_ID}
    - REDDIT_CLIENT_SECRET=${REDDIT_CLIENT_SECRET}
    - REDDIT_CALLBACK_URL=${REDDIT_CALLBACK_URL}
    - BOX_CLIENT_ID=${BOX_CLIENT_ID}
    - BOX_CLIENT_SECRET=${BOX_CLIENT_SECRET}
    - DROPBOX_CLIENT_ID=${DROPBOX_CLIENT_ID}
    - DROPBOX_CLIENT_SECRET=${DROPBOX_CLIENT_SECRET}
    - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
    - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
    - EMAIL_HOST=${EMAIL_HOST}
    - EMAIL_PORT=${EMAIL_PORT}
    - EMAIL_FROM_ADDRESS=${EMAIL_FROM_ADDRESS}
    - EMAIL_PASSWORD=${EMAIL_PASSWORD}
    - SINGLE_USER=${SINGLE_USER}
    - CILOGON_CLIENT_ID=${CILOGON_CLIENT_ID}
    - CILOGON_CLIENT_SECRET=${CILOGON_CLIENT_SECRET}
    - CILOGON_CALLBACK_URL=${CILOGON_CALLBACK_URL}
    volumes:
    - "smile_content_data:/tmp"
    - "smile_tag:${HOME}/smile"
    restart: unless-stopped

  smile-graphql:
#    build: /Users/cwang138/Documents/Macroscope/SMILE/www/graphql
    image: socialmediamacroscope/smile_graphql:0.1.0
    depends_on:
    - smile-server
    ports:
    - "5050:5050"
    command: npm run docker-start
    environment:
    - DOCKERIZED=${DOCKERIZED}
    - TWITTER_CONSUMER_KEY=${TWITTER_CONSUMER_KEY}
    - TWITTER_CONSUMER_SECRET=${TWITTER_CONSUMER_SECRET}
    restart: unless-stopped

  clowder-list:
    image: socialmediamacroscope/clowder_list:0.1.0
    depends_on:
      - rabbitmq
    command: python3 ./rabbitmq_handler.py
    environment:
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - CLOWDER_BASE_URL=${CLOWDER_BASE_URL}
      - CLOWDER_GLOBAL_KEY=${CLOWDER_GLOBAL_KEY}
      - QUEUE_NAME=lambda_list_clowder
    restart: unless-stopped

  clowder-create-space:
    image: socialmediamacroscope/clowder_create_space:0.1.0
    depends_on:
      - rabbitmq
    command: python3 ./rabbitmq_handler.py
    environment:
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - CLOWDER_BASE_URL=${CLOWDER_BASE_URL}
      - QUEUE_NAME=clowder_create_space
    restart: unless-stopped

  clowder-create-dataset:
    image: socialmediamacroscope/clowder_create_dataset:0.1.0
    depends_on:
      - rabbitmq
    command: python3 ./rabbitmq_handler.py
    environment:
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - CLOWDER_BASE_URL=${CLOWDER_BASE_URL}
      - QUEUE_NAME=lambda_invoke_clowder
    restart: unless-stopped

  clowder-create-collection:
    image: socialmediamacroscope/clowder_create_collection:0.1.0
    depends_on:
      - rabbitmq
    command: python3 ./rabbitmq_handler.py
    environment:
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - CLOWDER_BASE_URL=${CLOWDER_BASE_URL}
      - QUEUE_NAME=clowder_create_collection
    restart: unless-stopped

  clowder-upload-file:
    image: socialmediamacroscope/clowder_upload_file:0.1.2
    depends_on:
      - rabbitmq
    command: python3 ./rabbitmq_handler.py
    environment:
      - MINIO_PUBLIC_ACCESS_URL=${MINIO_PUBLIC_ACCESS_URL}
      - AWS_ACCESSKEY=${AWS_ACCESSKEY}
      - AWS_ACCESSKEYSECRET=${AWS_ACCESSKEYSECRET}
      - BUCKET_NAME=${BUCKET_NAME}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - CLOWDER_BASE_URL=${CLOWDER_BASE_URL}
      - QUEUE_NAME=lambda_upload_clowder
    restart: unless-stopped

volumes:
  smile_content_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      # put your own local data path here
      device: "${HOME}/smile_data"

  smile_user:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: "${HOME}/smile_user"

  smile_tag:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: "${HOME}/smile"
