FROM ubuntu:18.04

RUN apt-get -qq -y update && apt-get -qq -y install cron

RUN mkdir -p /scripts
WORKDIR /scripts

# copy paste python scripts
COPY . ./

# install dependency libraries
RUN apt-get update
RUN apt-get -y install python3-pip

# install dependency libraries and download required data
RUN pip3 install -r requirement.txt