FROM ubuntu:18.04

RUN mkdir -p /scripts
WORKDIR /scripts

# copy paste python scripts
COPY . ./

# install dependency libraries
RUN apt-get update
RUN apt-get -y install python3-pip

# install dependency libraries and download required data
RUN pip3 install -r requirement.txt
RUN python3 -m nltk.downloader -d /usr/local/share/nltk_data punkt vader_lexicon sentiwordnet