FROM python:3

RUN apt-get -qq -y update && apt-get -qq -y install cron

RUN mkdir -p /scripts
WORKDIR /scripts

COPY . ./

RUN pip install --no-cache-dir -r requirement.txt

# cron job clean tmp folder
RUN chmod u+x ./clear_cache.sh
RUN chmod 0644 ./clear_cache_cron
RUN crontab ./clear_cache_cron